//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TBProjBackend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Error
    {
        public int ErrorLogID { get; set; }
        public string ErrorDescription { get; set; }
        public System.DateTime ErrorTime { get; set; }
        public string UserName { get; set; }
    }
}
