//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TBProjBackend.Models
{
    using System;
    
    public partial class FrequencyCombinedListItem
    {
        public Nullable<int> TermID { get; set; }
        public string TermName { get; set; }
        public Nullable<int> ListenCount { get; set; }
        public Nullable<int> ClickCount { get; set; }
    }
}
