//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TBProjBackend.Models
{
    using System;
    
    public partial class TopTenTerm
    {
        public int TermID { get; set; }
        public string TermName { get; set; }
        public int VerbalHitCount { get; set; }
        public int ClickHitCount { get; set; }
    }
}
